<?xml version="1.0"?>
<robot xmlns:xacro="http:www.ros.org/wiki/xacro">
    <xacro:property name="camera_lenght" value="0.01" />
    <xacro:property name="camera_width" value="0.1" />
    <xacro:property name="camera_height" value="0.05" />

    <link name="camera_link">
        <visual>
            <!-- Here it really does not matter -->
            <geometry>
                <box size="${camera_lenght} ${camera_width} ${camera_height}" />
            </geometry>
            <material name="grey" />
        </visual>
        <collision>
            <geometry>
                <box size="${camera_lenght} ${camera_width} ${camera_height}" />
            </geometry>
        </collision>
        <xacro:box_inertia m="0.1" l="${camera_lenght}" w="${camera_width}" h="${camera_height}"
            xyz="0 0 0" rpy="0 0 0" />
    </link>

    <link name="camera_link_optical">
    </link>

    <joint name="base_camera_joint" type="fixed">
        <parent link="base_link" />
        <child link="camera_link" />
        <origin xyz="${(base_length + camera_lenght) / 2.0} 0 ${base_height / 2.0}" rpy="0 0 0" />
    </joint>

    <joint name="camera_optical_joint" type="fixed">
        <!-- these values have to be these values otherwise the gazebo camera
            image won't be aligned properly with the frame it is supposedly
            originating from -->
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
        <parent link="camera_link" />
        <child link="camera_link_optical" />
    </joint>


    <gazebo reference="camera_link">
        <material>Gazebo/Red</material>
        <sensor name="camera_sensor" type="camera">
            <!-- Position and orientation (we set it up with the joint that is a best practice) -->
            <pose>0 0 0 0 0 0</pose>
            <!-- You can set it to false later -->
            <visualize>true</visualize>
            <!-- Update in hertz -->
            <update_rate>10.0</update_rate>

            <plugin name="plugin_name" filename="libgazebo_ros_camera.so">
                <!--
                https://github.com/ros-simulation/gazebo_ros_pkgs/blob/ros2/gazebo_plugins/include/gazebo_plugins/gazebo_ros_camera.hpp -->
                <frame_name>camera_link_optical</frame_name>
            </plugin>
        </sensor>
    </gazebo>
</robot>